export const DEFAULT_PREFIX = '@@tcr';

// Twilio client events dispatched action types
export const DEVICE_EVENT_CANCEL = 'DEVICE_EVENT_CANCEL';
export const DEVICE_EVENT_CONNECT = 'DEVICE_EVENT_CONNECT';
export const DEVICE_EVENT_DISCONNECT = 'DEVICE_EVENT_DISCONNECT';
export const DEVICE_EVENT_ERROR = 'DEVICE_EVENT_ERROR';
export const DEVICE_EVENT_INCOMING = 'DEVICE_EVENT_INCOMING';
export const DEVICE_EVENT_OFFLINE = 'DEVICE_EVENT_OFFLINE';
export const DEVICE_EVENT_READY = 'DEVICE_EVENT_READY';

// User dispatched action types
export const DEVICE_SETUP = 'DEVICE_SETUP';
export const DEVICE_DESTROY = 'DEVICE_DESTROY';
export const DEVICE_SET_INPUT_DEVICE = 'DEVICE_SET_INPUT_DEVICE';
export const DEVICE_SET_OUTPUT_DEVICE = 'DEVICE_SET_OUTPUT_DEVICE';
export const DEVICE_TEST_OUTPUT_DEVICE = 'DEVICE_TEST_OUTPUT_DEVICE';

export const UNHANDLED_ERROR = 'UNHANDLED_ERROR';
