name: "Bundlewatch Github Action"

on:
  pull_request: 
    types: [synchronize, opened]

jobs:
  bundlewatch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: Borales/actions-yarn@v2.1.0
    - run: npm ci
    - uses: jackyef/bundlewatch-gh-action@master
      with:
        bundlewatch-github-token: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}